#pragma once 

#define FOREACH_EXPR_AST(EACTION) \
    EACTION(EXPR_NONE) \
    EACTION(EXPR_ADD) \
    EACTION(EXPR_SUB) \
    EACTION(EXPR_MUL) \
    EACTION(EXPR_DIV) \
    EACTION(EXPR_CALL)\
    EACTION(EXPR_INDEX) \
    EACTION(EXPR_VAL) \
    EACTION(EXPR_CONSTANT) \
    EACTION(EXPR_DECL_BLOCK) \
